# 多设备并行测试配置
pixel_5:
  platformName: "Android"
  deviceName: "emulator-5554"
  udid: "emulator-5554"
  appPackage: "com.curiousmax.kidstales"
  appActivity: "feature.splash.SplashActivity"
  automationName: "UiAutomator2"
  unicodeKeyboard: true
  resetKeyboard: true
  noReset: true
  autoGrantPermissions: true
  newCommandTimeout: 300
  skipServerInstallation: false
  settings[enableNotificationListener]: true
  settings[waitForIdleTimeout]: 0


#  - deviceName: "emulator-5556"
#    platformName: "Android"
#    platformVersion: "11"
#    udid: "emulator-5556"
#    systemPort: "8201"
#
#  - deviceName: "iPhone_12"
#    platformName: "iOS"
#    platformVersion: "14.5"
#    udid: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
#    wdaLocalPort: "8100"
