# 多设备并行测试配置
devices:
  - deviceName: "emulator-5554"
    platformName: "Android"
    platformVersion: "10"
    udid: "emulator-5554"
    systemPort: "8200"

#  - deviceName: "emulator-5556"
#    platformName: "Android"
#    platformVersion: "11"
#    udid: "emulator-5556"
#    systemPort: "8201"
#
#  - deviceName: "iPhone_12"
#    platformName: "iOS"
#    platformVersion: "14.5"
#    udid: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
#    wdaLocalPort: "8100"
